# fly.toml app configuration file generated for test-toolkit-ww5vxq on 2024-11-20T10:21:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-toolkit-ww5vxq'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
